units:
  KeyX: cx
  KeyY: cy
  PlateX: KeyX + 2
  PlateY: KeyY + 2
  ControllerOffset: 7
  StandoffSize: 5

points:
  zones:
    main:
      anchor.shift: [50, -100]
      key:
        padding: 1KeyY
        spread: 1KeyX
      columns:
        pinKeyY:
          rows:
            top: { column_net: P0, led_din: LED_DATA, led_dout: led1 }
            home: { column_net: P1, led_din: led1, led_dout: led2 }
            bottom: { column_net: P2, led_din: led2, led_dout: led3 }
        ring:
          key.stagger: 0.7KeyY
          rows:
            top: { column_net: P3, led_din: led3, led_dout: led4 }
            home: { column_net: P4, led_din: led4, led_dout: led5 }
            bottom: { column_net: P5, led_din: led5, led_dout: led6 }
        middle:
          key.stagger: 0.25KeyY
          rows:
            top: { column_net: P6, led_din: led6, led_dout: led7 }
            home: { column_net: P7, led_din: led7, led_dout: led8 }
            bottom: { column_net: P8, led_din: led8, led_dout: led9 }
        index:
          key.stagger: -0.2KeyY
          rows:
            top: { column_net: P9, led_din: led9, led_dout: led10 }
            home: { column_net: P10, led_din: led10, led_dout: led11 }
            bottom: { column_net: P14, led_din: led11, led_dout: led12 }
        inner:
          key.stagger: -0.15KeyY
          rows:
            top: { column_net: P15, led_din: led12, led_dout: led13 }
            home: { column_net: P16, led_din: led13, led_dout: led14 }
            bottom: { column_net: P18, led_din: led14, led_dout: led15 }
      rows:
        bottom:
        home:
        top:
    thumb:
      key:
        padding: 1KeyY
        spread: 1KeyX
      anchor:
        ref: main_index_bottom
        shift: [-0.285KeyX, -1.238KeyY]
      columns:
        near:
          key.name: thumb_near
          key.column_net: P19
          key.led_din: led15
          key.led_dout: led16
        mid:
          key.splay: -15
          key.origin: [-0.5KeyX, -0.5KeyY]
          key.name: thumb_mid
          key.column_net: P20
          key.led_din: led16
          key.led_dout: led17
        far:
          key.splay: -15
          key.origin: [-0.5KeyX, -0.5KeyY]
          key.name: thumb_far
          key.column_net: P21
          key.led_din: led17
          key.led_dout: LED_DOUT
      rows:
        thumb-cluster:

outlines:
  mcu:
    - what: rectangle
      where:
        - ref: main_inner_top
          shift: [17.9, -16.75 - ControllerOffset]
      size: [24.5, 66.5]
  keys:
    - what: rectangle
      where: true
      size: [PlateX, PlateY]
  thumbs:
    - what: polygon
      operation: stack
      points:
        - ref: thumb_near
          shift: [-0.5PlateX, 0.85PlateY]
        - ref: main_inner_bottom
          shift: [0.45PlateX, -0.5PlateY]
        - ref: thumb_far
          shift: [-0.5PlateX, 0.5PlateY]
        - ref: thumb_far
          shift: [0.5PlateX, 0.65PlateY]
        - ref: thumb_far
          shift: [0.5PlateX, -0.5PlateY]
        - ref: thumb_far
          shift: [-0.5PlateX, -0.5075PlateY]
        - ref: thumb_near
          shift: [0.5PlateX, -0.5PlateY]
        - ref: thumb_near
          shift: [-0.5PlateX, -0.5PlateY]
  combined: [keys, thumbs, mcu]
  board_outline:
    - name: combined
      expand: 0.1

pcbs:
  scoot:
    template: kicad8
    outlines:
      main:
        outline: board_outline
    footprints:
      choc_hotswap:
        what: ceoloide/switch_choc_v1_v2
        where: true
        params:
          from: "{{column_net}}"
          to: GND
          include_corner_marks: true
          include_keycap: true
          keycap_height: 16.5
          keycap_width: 17.5
          reversible: true
          hotswap: true
          choc_v2_support: false

      per_key_led:
        what: ceoloide/led_sk6812mini-e
        where: true
        params:
          reversible: true
          reverse_mount: true
          P4: "{{led_din}}"
          P2: "{{led_dout}}"
        adjust:
          shift: [0, -4.7]

      mcu:
        what: xonha/mcu_rp2040_pro_micro
        where:
          - ref: main_inner_home
            shift: [19.8, 15.6 - ControllerOffset]
        params:
          reverse_mount: true
          include_boot: false
          include_gp25: false
          reversible: true
          GP0: P0
          GP1: P1
          GP2: P2
          GP3: P3
          GP4: P4
          GP5: P5
          GP6: P6
          GP7: P7
          GP8: P8
          GP9: P9
          GP10: P10
          GP11: P14
          GP12: P15
          GP13: P16
          GP14: P18
          GP15: P19
          GP16: P20
          GP18: P21
          GP20: LED_DATA
          GP21: RE_A
          GP22: RE_B
          GP23: UART

      roller:
        what: xonha/roller_encoder_evqwgd001
        where:
          - ref: thumb_far
            shift: [-6, KeyY + 1]
            rotate: 20
        params:
          A: RE_A
          B: RE_B
          C: GND
          D: GND

      reset:
        what: ceoloide/reset_switch_tht_top
        params:
          reversible: true
        where:
          - ref: main_inner_home
            shift: [14, -5.5 - ControllerOffset]
            rotate: 90

      trrs:
        what: ceoloide/trrs_pj320a
        where:
          - ref: main_inner_home
            shift: [30.2, -5 - ControllerOffset]
            rotate: -90
        params:
          reversible: true
          symmetric: true
          TP: RAW
          R2: UART
          SL: GND

      hole_1:
        what: ceoloide/mounting_hole_npth
        where:
          - ref: main_ring_home
            shift: [-0.5KeyX, -0.2KeyY]
        params:
          hole_size: StandoffSize
          hole_drill: StandoffSize
      hole_2:
        what: ceoloide/mounting_hole_npth
        where:
          - ref: main_inner_top
            shift: [-0.5KeyX, -1.35KeyY]
        params:
          hole_size: StandoffSize
          hole_drill: StandoffSize
